victorkachalin/blog/urls.py
#coding: utf-8
# from django.conf.urls import patterns, url

# from blog.views import PostsListView, PostDetailView 

# urlpatterns = patterns('',
# url(r'^$', BlogListView.as_view(), name='list'), # то есть по URL http://имя_сайта/blog/ 
#                                                # будет выводиться список постов
# url(r'^(?P<pk>\d+)/$', PostDetailView.as_view())

# ) # а по URL http://имя_сайта/blog/число/ 
#                                               # будет выводиться пост с определенным номером

victorkachalin/shop/models.py
# coding: utf-8
import uuid
from django.db import models
from photologue.models import Photo

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.CharField(max_length=50,unique=True)
    link_text = models.CharField(max_length=255,unique=True, help_text=u'Текст ссылки на товар')
    price = models.IntegerField()
    options =  models.CharField(max_length=255,unique=False, blank = True, help_text=u'Доступные покупателю варианты товара на выбор (генерируется drop-down список). Варианты разделяются запятой с пробелом. Несколько списков разделяются символом #') 
    is_original_needed = models.BooleanField(default = False, help_text=u'Нужно ли иметь оригинал рисунка, чтобы это продавать')  
    def __unicode__(self):
        return self.name


    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары" 

    # def save(self, *args, **kwargs):
    #     if self.options:
    #         result = []
    #         str = self.options
    #         biglist = str.split('#')
    #         for i in range(len(biglist)):
    #             result.append(biglist[i].split(', '))
    #         self.options = result    

    #     super(Item, self).save(*args, **kwargs)        

def get_img_src(slug):
    photo = Photo.objects.get(title_slug=slug)
    return photo.get_admin_thumbnail_url()



class Order(models.Model):
    name = models.CharField(('Имя заказчика'), max_length=255,unique=False)
    email = models.EmailField()
    address = models.CharField(('Адрес'), max_length=255,unique=False, blank=True, help_text=u'Адрес доставки, если выбрана доставка почтой')
    phone = models.CharField(('Телефон'), max_length=255,unique=False)
    merchandise_id = models.CharField(('Что заказано'), max_length=255,unique=False)
    photo_id = models.CharField(('Название рисунка'), max_length=255, unique=False, blank=True)
    extra_field = models.CharField(('Детали'), max_length=255,unique=False)
    created_at = models.DateTimeField(auto_now_add = True)
    order_id = models.IntegerField(('Номер'),unique=True, blank=True, help_text=u'Уникальный номер заказа')
    postal = models.BooleanField(('Доставка почтой'),default = False)
    meeting = models.BooleanField(('Личная встреча'),default = False)

    def admin_thumbnail(self):
   
        return '<a href="%s"><img src="%s"></a>' % ('http://victorkachalin.ru/gallery/'+self.photo_id, 'http://victorkachalin.ru/'+get_img_src(self.photo_id))
    admin_thumbnail.allow_tags = True

    def __unicode__(self):
        return str(self.order_id) #self.name+ "   %s" % str(self.created_at)[:16]
    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы" 
    def save(self, *args, **kwargs):
        if self.address:
            self.postal = True
            self.meeting = False
        else:
            self.postal = False
            self.meeting = True    
  

        super(Order, self).save(*args, **kwargs)  

victorkachalin/shop/forms.py
# coding: utf-8
import re
from django import forms
from django.forms import ModelForm
from django.forms.models import fields_for_model
from shop.models import Order


class PhoneField(forms.Field):
    phoneMatchRegex = re.compile(r"^\d{10}$")
    phoneSplitRegex = re.compile(r"^\d{10}$")
 
    def clean(self, value):
        if not value:
            return ""
        if not self.phoneMatchRegex.match(value):
            raise forms.ValidationError("Неверный телефонный номер. Введите десятизначный номер (без восьмерки)")
        
 
        # Always return the cleaned data.
        return value

class OrderForm(ModelForm):
    class Meta:
        model = Order
        #fields = ['name', 'email', 'address', 'phone', 'merchandise_id', 'extra_field']
    CHOICES=[
         ('select 1','Получу при личной встрече в Москве на м. Теплый Стан'), ('select 2','Доставка почтой России'), ]

    delivery = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect() )
    address = forms.CharField(required = False, label ='Адрес')
    #merchandise_id = forms.CharField( required=False)
    phone = PhoneField(required = True)
    extra_field = forms.CharField(required = False)   
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs['pattern'] = "[0-9]{10}"
        self.fields['phone'].widget.attrs['placeholder'] = "9651112233"
        self.fields['phone'].label = 'Телефон'
        self.fields['delivery'].label = 'Доставка'
        self.fields['name'].label = 'Имя'
        self.fields['email'].label = 'E-mail'

class EditOrderForm(OrderForm):
    class Meta:
        model = Order
        exclude = ('order_id','merchandise_id', 'extra_field', 'created_at', 'photo_id', 'postal', 'meeting')


form = OrderForm(initial={'delivery': 'select 1'})


victorkachalin/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Виктор Качалин. Поэт, философ, художник.</title>
<!-- THE STYLES -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "styles/superfish.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/style.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/fonts.css"%}"/>

  <link rel="stylesheet" type="text/css" href="/static/styles/jquery.ad-gallery.css">
<!--[if lte IE 6]>
<link href="styles/style_ie6.css" rel="stylesheet" type="text/css" />  
<script type="text/javascript" src="script/supersleight.js"></script>
<![endif]-->
<!--[if lte IE 7]>
<link href="styles/style_ie7.css" rel="stylesheet" type="text/css" />  
<![endif]-->
<!--[if lte IE 8]>
<link href="styles/style_ie8.css" rel="stylesheet" type="text/css" />  
<![endif]-->
<!--END THE STYLES -->
<!-- SCRIPTS -->
<script type="text/javascript" src="{% static "script/jquery-1.4.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.tools.min.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.tools.min.js" %}"></script>
<script type="text/javascript" src="/static/script/jquery.ad-gallery.js"></script>
<script type="text/javascript" src="{% static "script/superfish.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.galleriffic.js" %}"></script>
<script type="text/javascript" src="{% static "script/slider.js" %}"></script>
<script type="text/javascript" src="{% static "script/script.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.opacityrollover.js" %}"></script>

<script type="text/javascript">
$(function(){
  pexetoSite.initSite();
  $('#slider').slider({thumbContainerId:'slider-navigation'});
  $('ul.sf-menu').superfish();
});

</script>

<!-- END SCRIPTS -->
</head>
<body>

<div id="main-container">
  <div id="line-top"></div>
  <div id="header" >
    <div id="logo-container" class="center"><a href="http://www.victorkachalin.ru" ></a></div>
    <div id="menu-container">
      <div class="hr"></div>
      <div id="menu" class="center">


      {% load mptt_tags %}
<ul class="sf-menu">
    {% recursetree nodes %}
        <li>
            <a href="{{node.get_absolute_url}}">{{ node.name }}</a>
            {% if not node.is_leaf_node %}
            {% if children %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}   
            {% endif %}
        </li>
    {% endrecursetree %}

      </div>
      <div class="hr"></div>
    </div>
  </div>

{% block page %}
<!--   {% block content %}
  {% endblock %}
  
  {% block sidebar %}
  {% endblock %} -->
{% endblock %}

  <!-- FOOTER START -->
  <div id="footer-container">
    <div class="hr"></div>
    <div id="footer-line"></div>
    <div id="footer" class="center">
      <div class="columns-wrapper">
        <div class="four-columns">
          <h4>Свежие стихи</h4>
          <div class="double-hr"></div>
          <ul>
            {% for post in poetry %}
            {% if forloop.counter < 6 %}
            <li><a href="{{post.get_absolute_url}}">{{post.name}}</a></li>
            {% endif %}
            {% endfor %}
          </ul>
        </div>
        <div class="four-columns">
          <h4>Блог</h4>
          <div class="double-hr"></div>
          <ul>
            {% for post in blogposts %}
            {% if forloop.counter < 4 %}
            

            <li><a href="{{post.get_absolute_url}}">{{post.text|striptags|truncatewords:9}}</a></li>

            {% endif %}
            {% endfor %}
          </ul>
        </div>
        <div class="four-columns">
          <h4>Социальные сети</h4>
          <div class="double-hr"></div>
          
          <div id="footer-icons">
            <ul>

              <li><a href="http://www.facebook.com/victor.kachalin"><img src="{% static "images/icons/facebook_2.png"%}" alt="ico2n" /></a></li>
               <li><a href="http://vk.com/id188264372"><img src="{% static "images/icons/vk.png"%}" alt="ico2n" /></a></li>
                <li><a href="#"><img src="{% static "images/icons/yandex.png"%}" alt="ico2n" /></a></li>
                 <li><a href="http://my.mail.ru/mail/alchantov/"><img src="{% static "images/icons/mail_ru_2.png"%}" alt="ico2n" /></a></li>
                 <li><a href="http://duhov-vek.livejournal.com"><img src="{% static "images/icons/livejournal.png"%}" alt="ico2n" /></a></li>
                 <li><a href="http://www.blogger.com/profile/05145413765623828197"><img src="{% static "images/icons/blogger.png"%}" alt="ico2n" /></a></li>
            
            </ul>
          </div>
        </div>
        <div class="four-columns-4">
          <h4>Последние рисунки</h4>
          <div class="double-hr"></div>
          <div id="footer-projcets">
            <ul>
              {% for pic in pictures %}
              {% if forloop.counter < 5 %}
              <li><a href="{{pic.get_absolute_url}}"><img src="{{pic.get_footer_url}}" alt="{{pic.title}}" /></a></li>
              {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="copyrights" >
    <h5 class="center" >© Copyright Anthology Premium Website Template - Designed by <a href="http://themeforest.net/user/pexeto">Pexeto</a></h5>
  </div>
  <!-- FOOTER ENDS -->
</div>



</body>
</html>

victorkachalin/templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Витин сайт - Base2</title>
<!-- THE STYLES -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "styles/superfish.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/style.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/fonts.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "styles/prettyPhoto.css"%}"/>
<!--[if lte IE 6]>
<link href="styles/style_ie6.css" rel="stylesheet" type="text/css" />  
<script type="text/javascript" src="script/supersleight.js"></script>
<![endif]-->
<!--[if lte IE 7]>
<link href="styles/style_ie7.css" rel="stylesheet" type="text/css" />  
<![endif]-->
<!--[if lte IE 8]>
<link href="styles/style_ie8.css" rel="stylesheet" type="text/css" />  
<![endif]-->
<!--END THE STYLES -->
<!-- SCRIPTS -->
<script type="text/javascript" src="{% static "script/jquery-1.4.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.tools.min.js" %}"></script>
<script type="text/javascript" src="{% static "script/superfish.js" %}"></script>
<script type="text/javascript" src="{% static "script/jquery.prettyPhoto.js" %}"></script>
<script type="text/javascript" src="{% static "script/slider.js" %}"></script>
<script type="text/javascript" src="{% static "script/script.js" %}"></script>
<script type="text/javascript">
$(function(){
	pexetoSite.initSite();
});

</script>
<!-- END SCRIPTS -->
</head>
<body>

<div id="main-container">
  <div id="line-top"></div>
  <div id="header" >
    <div id="logo-container" class="center"><a href="index.html" ></a></div>
    <div id="menu-container">
      <div class="hr"></div>
      <div id="menu" class="center">


      {% load mptt_tags %}
<ul class="sf-menu">
    {% recursetree nodes %}
        <li>
            <a href="{{node.get_absolute_url}}">{{ node.name }}</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}

      </div>
      <div class="hr"></div>
    </div>
  </div>

{% block page %}
<!--   {% block content %}
  {% endblock %}
  
  {% block sidebar %}
  {% endblock %} -->
{% endblock %}

  <!-- FOOTER START -->
  <div id="footer-container">
    <div class="hr"></div>
    <div id="footer-line"></div>
    <div id="footer" class="center">
      <div class="columns-wrapper">
        <div class="four-columns">
          <h4>More Projects</h4>
          <div class="double-hr"></div>
          <ul>
            <li><a href="#">Create a Realistic Picture Frame With Photoshop</a></li>
            <li><a href="#">Psdtuts joins the Smashing Network </a></li>
            <li><a href="#">A Sneak Peek at Premium for Non-Members </a></li>
            <li><a href="#">Create Gold Ornamental Text in Photoshop </a></li>
          </ul>
        </div>
        <div class="four-columns">
          <h4>laest from TWTTER</h4>
          <div class="double-hr"></div>
          <ul>
            <li><a href="#">A new update of my Perception WordPress theme is now available- it includes a widgetized footer- http://bit.ly/cjHBqG</a></li>
            <li><a href="#">Just finished the new addition to my Perception WordPress theme - a widgetized footer, the update is in query </a></li>
          </ul>
        </div>
        <div class="four-columns">
          <h4>Sociable Links</h4>
          <div class="double-hr"></div>
          <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has more or less normal distribution of letters </p>
          <div id="footer-icons">
            <ul>
              <li><a href="#"><img src="images/icons/delicious_32.png" alt="icon1" /></a></li>
              <li><a href="#"><img src="images/icons/facebook_32.png" alt="ico2n" /></a></li>
              <li><a href="#"><img src="images/icons/flickr_32.png" alt="icon3" /></a></li>
              <li><a href="#"><img src="images/icons/twitter_32.png" alt="icon4" /></a></li>
              <li><a href="#"><img src="images/icons/rss_32.png" alt="icon5" /></a></li>
            </ul>
          </div>
        </div>
        <div class="four-columns-4">
          <h4>Latest Projects</h4>
          <div class="double-hr"></div>
          <div id="footer-projcets">
            <ul>
              <li><a href="#"><img src="images/timthumb.jpg" alt="tumbnail2" /></a></li>
              <li><a href="#"><img src="images/timthumb2.jpg" alt="tumbnail3" /></a></li>
              <li><a href="#"><img src="images/timthumb3.jpg" alt="tumbnail4" /></a></li>
              <li><a href="#"><img src="images/timthumb4.jpg" alt="tumbnail5" /></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="copyrights" >
    <h5 class="center" >© Copyright Anthology Premium Website Template - Designed by <a href="http://themeforest.net/user/pexeto">Pexeto</a></h5>
  </div>
  <!-- FOOTER ENDS -->
</div>
</body>
</html>

victorkachalin/templates/base_homepage.html
{% extends 'base.html'  %}


{% block page %}


    <div id="slider-container">
      <div id="slider-container-shadow"></div>
      <div id="slider" class="center"> 

{% for photo in object %}

        <img src="{{ photo.get_homepage_url }}" alt="" />
{% endfor %}


         </div>
      <div id="slider-container-shadow-bottom"></div>
    </div>

<div id="slider-navigation-container">
      <div class="hr"></div>
      <div class="center relative">
        <div id="slider-navigation" >
          <!-- the small thumbnails will be displayed here -->
        </div>
      </div>
      <div class="hr"></div>
    </div>

 {% endblock %}   

victorkachalin/templates/base_sidebar.html
{% extends "base.html" %}

{% block sidebar %}
    <div class="sidebar">
      <div class="sidebar-box">
        <h4>Our Projects</h4>
        <div class="double-hr"></div>
        <ul id="sidebar-projects">
          <li><a href="#"><img  alt="" src="images/tumb.jpg" class="shadow-frame" /></a></li>
          <li><a href="#"><img  alt="" src="images/tumb9.jpg" class="shadow-frame" /></a></li>
          <li><a href="#"><img  alt="" src="images/tumb3.jpg" class="shadow-frame" /></a></li>
          <li><a href="#"><img  alt="" src="images/tumb7.jpg" class="shadow-frame" /></a></li>
        </ul>
      </div>
      <div class="sidebar-box">
        <h4>Categories</h4>
        <div class="double-hr"></div>
        <ul>
          <li><a href="#">Market Research</a></li>
          <li><a href="#">Business Planning</a></li>
          <li><a href="#">Presentation</a></li>
          <li><a href="#">Productivity</a></li>
          <li><a href="#">Your Career</a></li>
          <li><a href="#">General</a></li>
        </ul>
      </div>
      <div class="sidebar-box">
        <h4>Newsletter</h4>
        <div class="double-hr"></div>
        <p>Please Enter your email to sign up for our newsletter</p>
        <input type="text" />
        <a class="button-small"><span>Sign Up</span></a> </div>
    </div>
    {% endblock %}

victorkachalin/templates/cat_list.html
{% extends "page_sidebar.html" %}



{% block content %}
  <div id="content">
    <!-- <div id="content"> -->

    {% for post in object_list %}
      <div class="blog-post-wide">
        <h1><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h1>
        <div class="double-hr"></div>
 <!--        <div class="post-info">
          <ul>
            <li><a href="#">{{ post.date }}</a></li>
            <li><a href="#"> <span class="no-caps"> by</span> pexeto </a></li>
            <li class="post-info-categories"><a href="#"> Career</a>, <a href="#">Productivity</a> , <a href="#">General</a> </li>
            <li class="post-info-comments"><a href="#">23 Comments </a></li>
          </ul>
        </div> -->
        <!-- <a href=""> <img src="images/post_img.jpg" alt="" class="shadow-frame" /> </a> -->
        <p> {{ post.description }} </p>
      </div>
       {% empty %}
    <p>Нет постов</p>
    {% endfor %}
    <!-- </div> -->
  </div>
    {% endblock %}
   
  </div>

victorkachalin/templates/newpost_detail.html
{% extends "page_sidebar.html" %}



{% block content %}

<div id="content">
   
     <div class="blog-post">
        <h1><a href="">{{object.name}}</a></h1>
        <div class="double-hr"></div>
        {{object.text|safe}}
      </div>

  <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'victorkachalin'; // required: replace example with your forum shortname
        var disqus_identifier = 'newpost_{{object.id}}';
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
    </div>
    
 
      
      {% endblock content %}
 

victorkachalin/templates/newpost_list.html
{% extends "page_sidebar.html" %}

{% block content %}
  <!-- <div id="full-width"> -->
    <div id="content">

    {% for post in object_list %}
      <div class="blog-post-wide">
        <h1><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h1>
        <div class="double-hr"></div>
        <div class="post-info">
          <ul>
            <li><a href="#">{{ post.date }}</a></li>
            <li class="post-info-comments"><a data-disqus-identifier="newpost_{{post.id}}" href="http://victorkachalin.ru{{post.get_absolute_url}}#disqus_thread">Комментарии</a></li>
          </ul>
        </div>
      
        <p> {{ post.text|safe|truncatewords:20}} <br><a href="{{ post.get_absolute_url }}" class="read-more"> Читать полностью....</a> </p>
      </div>
       {% empty %}
    <p>Нет постов</p>
    {% endfor %}
<br>
     {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/{{cslug}}/list/page{{ page_obj.previous_page_number }}">Назад</a>
                {% endif %}
                <span class="page-current">
                    (Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}).
                </span>
                {% if page_obj.has_next %}
                    <a href="/{{cslug}}/list/page{{ page_obj.next_page_number }}">Вперед</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <!-- </div> -->
  <!-- </div> -->



    </div>



  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'victorkachalin'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>
    {% endblock content %}
   

victorkachalin/templates/order.html
{% extends "photologue/root.html" %}

{% load photologue_tags %}


{% block content %}

    <div id="portfolio-preview-container"><div id="portfolio-preview"><div>	
    <h1>Заказ # {{ order.order_id }}</h1>		
<p> <b>Имя:</b> {{order.name}}</p>
<p> <b>Телефон:</b> {{ order.phone }}</p>
<p> <b>Email:</b> {{ order.email }}</p>
{% if order.address %}
<p> <b>Доставка: </b>почтой России</p>
<p> <b>Адрес:</b> {{ order.address }}</p>
{% else %}
<p> <b>Доставка: </b>при личной встрече</p>
{% endif %}
{% if order.extra_field %}
<p> <b>Детали заказа:</b> {{ order.extra_field }}</p>
{% endif %}      

<p><b>Cтатус заказа:</b> {{ status|safe }}</p>

			</div>


{% if edit_button %}
<a href="http://www.victorkachalin.ru/shop/orders/{{ order.order_id }}/edit" class="button"><span>Изменить контактные данные</span></a> 

{% endif %}

{% if cancel_button %}
<a href="http://www.victorkachalin.ru/shop/orders/{{ order.order_id }}/delete" class="button"><span>Отменить заказ</span></a>  
{% endif %}


			</div>




<div class="sidebar">
<div class="sidebar-box">

    <div class="pricing-box three-columns">
          <h4><span>{{item.name}} "{{photo.title}}"</span></h4>
          <img src="{{ photo.get_shop_url }}" alt="" class="shadow-frame">
          <span class="price"> {{item.price}} рублей</span> <br>
         </div>
</div>
 
</div>
 </div>


  {% endblock %}

victorkachalin/templates/photo_buy.html
{% extends "photologue/root.html" %}

{% load photologue_tags %}


{% block content %}

    <div id="portfolio-preview-container"><div id="portfolio-preview"><div>			

<form action="" method="post" id="submit_form">{% csrf_token %}

    <div class="contact_form_input">
       
        <label for="id_subject"><h6>Ваше имя:</h6></label>
        {{ form.name }}
    {% if form.name.errors %}
          <div class="question_icon"></div>
          {% endif %}
    </div>
    <div class="contact_form_input">
       
        <label for="id_message"><h6>Телефон:</h6></label>
        {{ form.phone }}   {% if form.phone.errors %}
          <div class="question_icon"></div>
          {% endif %}
    </div>
    <div class="contact_form_input">
        
        <label for="id_sender"><h6>E-mail:</h6></label>
        {{ form.email }}   {% if form.email.errors %}
          <div class="question_icon"></div>
          {% endif %}
    </div>
    <div class="contact_form_input">
        <h6>
  
        {{ form.delivery }}</h6>
    </div>

       <div class="contact_form_input" id = "address_div">
        <label for="id_sender"><h6>Полный почтовый адрес:</h6></label>
        
  
        {{ form.address }}   {% if form.address.errors %}
          <div class="question_icon"></div>
          {% endif %}
    </div>

{% if opt %}

{% for list in opt %}

<div class="contact_form_input" id = "extra{{ forloop.counter }}">

<select>

{% for option in list %}
  <option value="{{ option }}">{{ option }}</option>
{% endfor %}

</select> 
<br>        
  
   
    </div>
{% endfor %}



{% endif %}
 <input type="hidden" name="extra_field" value="" id="id_extra_field" />

    <input type="hidden" name="merchandise_id" value="{{item.name}}" id="id_merchandise_id" />

    <input type="hidden" name="photo_id" value="{{id}}" id="id_photo_id" />

    {% if form.errors %}
          <div class="error_box"><b> <ul class="errorlist">
  {% if form.non_field_errors %}
    <li>{{ form.non_field_errors }}</li>
  {% endif %}
  {% for field in form %}
    {% if field.errors %}
      <li>
        {{ field.label }}:
        <ul class="errorlist">
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}
  {% endfor %}
</ul></div>
          {% endif %}
<br>
     <a href="" class="button" id="send_button"><span>{% if edit %} Сохранить изменения {% else %} Заказать {% endif %}</span></a>
    
</form>

			</div>
			</div>

<div class="sidebar">
<div class="sidebar-box">

    <div class="pricing-box three-columns">
          <h4><span>{{item.name}} "{{photo.title}}"</span></h4>
          <img src="{{ photo.get_shop_url }}" alt="" class="shadow-frame">
          <span class="price"> {{item.price}} рублей</span> <br>
         </div>
</div>
 
</div>
</div>
<script>

$( document ).ready(function() {
var extra_field = $("select option:selected").map(function() { return this.value; })
                                   .get().join(', ');
                                   console.log(extra_field)

$('#id_extra_field').val(extra_field)

});

</script>

  {% endblock %}

victorkachalin/templates/singlepage.html
{% extends "page_wide.html" %}

{% block content %}

{{object.text|safe}}


      
      {% endblock content%}